In [35]:
import numpy as np
import pandas as pd

df = pd.read_excel("donor full.xlsx")
df.head(5)

,Sr No.,Reference No (URN),Journal Date,Date of\nPurchase,Date of Expiry,Name of the Purchaser,Column7,Column8,Column9,Prefix,Bond\nNumber,Denominations,Issue Branch Code,Issue Teller,Status
0,1,1.201904e+18,2019-04-12,2019-04-12,2019-04-26,A B C INDIA LIMITED,NaN,NaN,NaN,TL,11448,1000000,1,5899230,Paid
1,2,1.201904e+18,2019-04-12,2019-04-12,2019-04-26,A B C INDIA LIMITED,NaN,NaN,NaN,TL,11447,1000000,1,5899230,Paid
2,3,1.201904e+18,2019-04-12,2019-04-12,2019-04-26,A B C INDIA LIMITED,NaN,NaN,NaN,TL,11441,1000000,1,5899230,Paid
3,4,1.201904e+18,2019-04-12,2019-04-12,2019-04-26,A B C INDIA LIMITED,NaN,NaN,NaN,OL,1113,100000,1,5899230,Paid
4,5,1.201904e+18,2019-04-12,2019-04-12,2019-04-26,A B C INDIA LIMITED,NaN,NaN,NaN,OL,1118,100000,1,5899230,Paid

In [36]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18871 entries, 0 to 18870
Data columns (total 15 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Sr No.                 18871 non-null  int64
 1   Reference No (URN)     18871 non-null  float64
 2   Journal Date           18871 non-null  datetime64[ns]
 3   Date of
Purchase       18871 non-null  datetime64[ns]
 4   Date of Expiry         18871 non-null  datetime64[ns]
 5   Name of the Purchaser  18871 non-null  object
 6   Column7                158 non-null    object
 7   Column8                97 non-null     object
 8   Column9                39 non-null     object
 9   Prefix                 18871 non-null  object
 10  Bond
Number            18871 non-null  int64
 11  Denominations          18871 non-null  int64
 12  Issue Branch Code      18871 non-null  int64
 13  Issue Teller           18871 non-null  int64
 14  Status                 18871 non-null  object
dtypes: datetime64[ns](3), float64(1), int64(5), object(6)
memory usage: 2.2+ MB

In [37]:
x = df.loc[df.Column9.notna()].index

In [38]:
df.loc[x]

,Sr No.,Reference No (URN),Journal Date,Date of\nPurchase,Date of Expiry,Name of the Purchaser,Column7,Column8,Column9,Prefix,Bond\nNumber,Denominations,Issue Branch Code,Issue Teller,Status
12330,12331,3.002023e+20,2023-04-06,2023-04-06,2023-04-20,INDER,NaN,NaN,THAKURDAS JAISINGHANI,OC,13653,10000000,300,7905165,Paid
12331,12332,3.002023e+20,2023-04-06,2023-04-06,2023-04-20,INDER,NaN,NaN,THAKURDAS JAISINGHANI,OC,13661,10000000,300,7905165,Paid
12332,12333,3.002023e+20,2023-04-06,2023-04-06,2023-04-20,INDER,NaN,NaN,THAKURDAS JAISINGHANI,OC,13657,10000000,300,7905165,Paid
12333,12334,3.002023e+20,2023-04-06,2023-04-06,2023-04-20,INDER,NaN,NaN,THAKURDAS JAISINGHANI,OC,13669,10000000,300,7905165,Paid
12334,12335,3.002023e+20,2023-04-06,2023-04-06,2023-04-20,INDER,NaN,NaN,THAKURDAS JAISINGHANI,OC,13659,10000000,300,7905165,Paid
12335,12336,3.002023e+20,2023-04-06,2023-04-06,2023-04-20,INDER,NaN,NaN,THAKURDAS JAISINGHANI,OC,13667,10000000,300,7905165,Paid
12336,12337,3.002023e+20,2023-04-06,2023-04-06,2023-04-20,INDER,NaN,NaN,THAKURDAS JAISINGHANI,OC,13655,10000000,300,7905165,Paid
12337,12338,3.002023e+20,2023-04-06,2023-04-06,2023-04-20,INDER,NaN,NaN,THAKURDAS JAISINGHANI,OC,13651,10000000,300,7905165,Paid
12338,12339,3.002023e+20,2023-04-06,2023-04-06,2023-04-20,INDER,NaN,NaN,THAKURDAS JAISINGHANI,OC,13663,10000000,300,7905165,Paid
12339,12340,3.002023e+20,2023-04-06,2023-04-06,2023-04-20,INDER,NaN,NaN,THAKURDAS JAISINGHANI,OC,13665,10000000,300,7905165,Paid
13438,13439,1.202304e+18,2023-04-12,2023-04-12,2023-04-26,PRAKASH DISTILLERY & CHEMICAL CO (P) LT,NaN,NaN,D,TL,14654,1000000,1,5054982,Paid
13439,13440,1.202304e+18,2023-04-12,2023-04-12,2023-04-26,PRAKASH DISTILLERY & CHEMICAL CO (P) LT,NaN,NaN,D,TL,14656,1000000,1,5054982,Paid
13440,13441,1.202304e+18,2023-04-12,2023-04-12,2023-04-26,PRAKASH DISTILLERY & CHEMICAL CO (P) LT,NaN,NaN,D,TL,14658,1000000,1,5054982,Paid
13441,13442,1.202304e+18,2023-04-12,2023-04-12,2023-04-26,PRAKASH DISTILLERY & CHEMICAL CO (P) LT,NaN,NaN,D,TL,14650,1000000,1,5054982,Paid
13442,13443,1.202304e+18,2023-04-12,2023-04-12,2023-04-26,PRAKASH DISTILLERY & CHEMICAL CO (P) LT,NaN,NaN,D,TL,14652,1000000,1,5054982,Paid
14120,14121,9.522023e+20,2023-07-10,2023-07-10,2023-07-24,R,R INFRATECH,INDIA,PRIVATE LIM,OC,1252,10000000,952,8487561,Paid
14121,14122,9.522023e+20,2023-07-10,2023-07-10,2023-07-24,R,R INFRATECH,INDIA,PRIVATE LIM,TL,2697,1000000,952,8487561,Paid
14122,14123,9.522023e+20,2023-07-10,2023-07-10,2023-07-24,R,R INFRATECH,INDIA,PRIVATE LIM,TL,2647,1000000,952,8487561,Paid
14123,14124,9.522023e+20,2023-07-10,2023-07-10,2023-07-24,R,R INFRATECH,INDIA,PRIVATE LIM,TL,2677,1000000,952,8487561,Paid
14124,14125,9.522023e+20,2023-07-10,2023-07-10,2023-07-24,R,R INFRATECH,INDIA,PRIVATE LIM,TL,2695,1000000,952,8487561,Paid
14125,14126,9.522023e+20,2023-07-10,2023-07-10,2023-07-24,R,R INFRATECH,INDIA,PRIVATE LIM,TL,2663,1000000,952,8487561,Paid
14126,14127,9.522023e+20,2023-07-10,2023-07-10,2023-07-24,R,R INFRATECH,INDIA,PRIVATE LIM,TL,2660,1000000,952,8487561,Paid
14127,14128,9.522023e+20,2023-07-10,2023-07-10,2023-07-24,R,R INFRATECH,INDIA,PRIVATE LIM,TL,2603,1000000,952,8487561,Paid
14128,14129,9.522023e+20,2023-07-10,2023-07-10,2023-07-24,R,R INFRATECH,INDIA,PRIVATE LIM,TL,2625,1000000,952,8487561,Paid
14129,14130,9.522023e+20,2023-07-10,2023-07-10,2023-07-24,R,R INFRATECH,INDIA,PRIVATE LIM,TL,2690,1000000,952,8487561,Paid
14130,14131,9.522023e+20,2023-07-10,2023-07-10,2023-07-24,R,R INFRATECH,INDIA,PRIVATE LIM,TL,2675,1000000,952,8487561,Paid
14131,14132,9.522023e+20,2023-07-10,2023-07-10,2023-07-24,R,R INFRATECH,INDIA,PRIVATE LIM,TL,2693,1000000,952,8487561,Paid
14132,14133,9.522023e+20,2023-07-10,2023-07-10,2023-07-24,R,R INFRATECH,INDIA,PRIVATE LIM,TL,2682,1000000,952,8487561,Paid
14133,14134,9.522023e+20,2023-07-10,2023-07-10,2023-07-24,R,R INFRATECH,INDIA,PRIVATE LIM,TL,2648,1000000,952,8487561,Paid
14134,14135,9.522023e+20,2023-07-10,2023-07-10,2023-07-24,R,R INFRATECH,INDIA,PRIVATE LIM,TL,2616,1000000,952,8487561,Paid
14135,14136,9.522023e+20,2023-07-10,2023-07-10,2023-07-24,R,R INFRATECH,INDIA,PRIVATE LIM,TL,2672,1000000,952,8487561,Paid
18232,18233,1.202401e+18,2024-01-08,2024-01-08,2024-01-22,PRAKASH DISTILLERY & CHEMICAL CO (P) LT,NaN,NaN,D,TL,15987,1000000,1,5898161,Paid
18233,18234,1.202401e+18,2024-01-08,2024-01-08,2024-01-22,PRAKASH DISTILLERY & CHEMICAL CO (P) LT,NaN,NaN,D,TL,15993,1000000,1,5898161,Paid
18234,18235,1.202401e+18,2024-01-08,2024-01-08,2024-01-22,PRAKASH DISTILLERY & CHEMICAL CO (P) LT,NaN,NaN,D,TL,15991,1000000,1,5898161,Paid
18235,18236,1.202401e+18,2024-01-08,2024-01-08,2024-01-22,PRAKASH DISTILLERY & CHEMICAL CO (P) LT,NaN,NaN,D,TL,15989,1000000,1,5898161,Paid
18236,18237,1.202401e+18,2024-01-08,2024-01-08,2024-01-22,PRAKASH DISTILLERY & CHEMICAL CO (P) LT,NaN,NaN,D,TL,15981,1000000,1,5898161,Paid
18237,18238,1.202401e+18,2024-01-08,2024-01-08,2024-01-22,PRAKASH DISTILLERY & CHEMICAL CO (P) LT,NaN,NaN,D,TL,15983,1000000,1,5898161,Paid
18238,18239,1.202401e+18,2024-01-08,2024-01-08,2024-01-22,PRAKASH DISTILLERY & CHEMICAL CO (P) LT,NaN,NaN,D,TL,15995,1000000,1,5898161,Paid
18239,18240,1.202401e+18,2024-01-08,2024-01-08,2024-01-22,PRAKASH DISTILLERY & CHEMICAL CO (P) LT,NaN,NaN,D,TL,15985,1000000,1,5898161,Paid

In [39]:
df[["Column7","Column8","Column9"]]=df[["Column7","Column8","Column9"]].fillna("")

In [40]:
df.loc[x]

,Sr No.,Reference No (URN),Journal Date,Date of\nPurchase,Date of Expiry,Name of the Purchaser,Column7,Column8,Column9,Prefix,Bond\nNumber,Denominations,Issue Branch Code,Issue Teller,Status
12330,12331,3.002023e+20,2023-04-06,2023-04-06,2023-04-20,INDER,,,THAKURDAS JAISINGHANI,OC,13653,10000000,300,7905165,Paid
12331,12332,3.002023e+20,2023-04-06,2023-04-06,2023-04-20,INDER,,,THAKURDAS JAISINGHANI,OC,13661,10000000,300,7905165,Paid
12332,12333,3.002023e+20,2023-04-06,2023-04-06,2023-04-20,INDER,,,THAKURDAS JAISINGHANI,OC,13657,10000000,300,7905165,Paid
12333,12334,3.002023e+20,2023-04-06,2023-04-06,2023-04-20,INDER,,,THAKURDAS JAISINGHANI,OC,13669,10000000,300,7905165,Paid
12334,12335,3.002023e+20,2023-04-06,2023-04-06,2023-04-20,INDER,,,THAKURDAS JAISINGHANI,OC,13659,10000000,300,7905165,Paid
12335,12336,3.002023e+20,2023-04-06,2023-04-06,2023-04-20,INDER,,,THAKURDAS JAISINGHANI,OC,13667,10000000,300,7905165,Paid
12336,12337,3.002023e+20,2023-04-06,2023-04-06,2023-04-20,INDER,,,THAKURDAS JAISINGHANI,OC,13655,10000000,300,7905165,Paid
12337,12338,3.002023e+20,2023-04-06,2023-04-06,2023-04-20,INDER,,,THAKURDAS JAISINGHANI,OC,13651,10000000,300,7905165,Paid
12338,12339,3.002023e+20,2023-04-06,2023-04-06,2023-04-20,INDER,,,THAKURDAS JAISINGHANI,OC,13663,10000000,300,7905165,Paid
12339,12340,3.002023e+20,2023-04-06,2023-04-06,2023-04-20,INDER,,,THAKURDAS JAISINGHANI,OC,13665,10000000,300,7905165,Paid
13438,13439,1.202304e+18,2023-04-12,2023-04-12,2023-04-26,PRAKASH DISTILLERY & CHEMICAL CO (P) LT,,,D,TL,14654,1000000,1,5054982,Paid
13439,13440,1.202304e+18,2023-04-12,2023-04-12,2023-04-26,PRAKASH DISTILLERY & CHEMICAL CO (P) LT,,,D,TL,14656,1000000,1,5054982,Paid
13440,13441,1.202304e+18,2023-04-12,2023-04-12,2023-04-26,PRAKASH DISTILLERY & CHEMICAL CO (P) LT,,,D,TL,14658,1000000,1,5054982,Paid
13441,13442,1.202304e+18,2023-04-12,2023-04-12,2023-04-26,PRAKASH DISTILLERY & CHEMICAL CO (P) LT,,,D,TL,14650,1000000,1,5054982,Paid
13442,13443,1.202304e+18,2023-04-12,2023-04-12,2023-04-26,PRAKASH DISTILLERY & CHEMICAL CO (P) LT,,,D,TL,14652,1000000,1,5054982,Paid
14120,14121,9.522023e+20,2023-07-10,2023-07-10,2023-07-24,R,R INFRATECH,INDIA,PRIVATE LIM,OC,1252,10000000,952,8487561,Paid
14121,14122,9.522023e+20,2023-07-10,2023-07-10,2023-07-24,R,R INFRATECH,INDIA,PRIVATE LIM,TL,2697,1000000,952,8487561,Paid
14122,14123,9.522023e+20,2023-07-10,2023-07-10,2023-07-24,R,R INFRATECH,INDIA,PRIVATE LIM,TL,2647,1000000,952,8487561,Paid
14123,14124,9.522023e+20,2023-07-10,2023-07-10,2023-07-24,R,R INFRATECH,INDIA,PRIVATE LIM,TL,2677,1000000,952,8487561,Paid
14124,14125,9.522023e+20,2023-07-10,2023-07-10,2023-07-24,R,R INFRATECH,INDIA,PRIVATE LIM,TL,2695,1000000,952,8487561,Paid
14125,14126,9.522023e+20,2023-07-10,2023-07-10,2023-07-24,R,R INFRATECH,INDIA,PRIVATE LIM,TL,2663,1000000,952,8487561,Paid
14126,14127,9.522023e+20,2023-07-10,2023-07-10,2023-07-24,R,R INFRATECH,INDIA,PRIVATE LIM,TL,2660,1000000,952,8487561,Paid
14127,14128,9.522023e+20,2023-07-10,2023-07-10,2023-07-24,R,R INFRATECH,INDIA,PRIVATE LIM,TL,2603,1000000,952,8487561,Paid
14128,14129,9.522023e+20,2023-07-10,2023-07-10,2023-07-24,R,R INFRATECH,INDIA,PRIVATE LIM,TL,2625,1000000,952,8487561,Paid
14129,14130,9.522023e+20,2023-07-10,2023-07-10,2023-07-24,R,R INFRATECH,INDIA,PRIVATE LIM,TL,2690,1000000,952,8487561,Paid
14130,14131,9.522023e+20,2023-07-10,2023-07-10,2023-07-24,R,R INFRATECH,INDIA,PRIVATE LIM,TL,2675,1000000,952,8487561,Paid
14131,14132,9.522023e+20,2023-07-10,2023-07-10,2023-07-24,R,R INFRATECH,INDIA,PRIVATE LIM,TL,2693,1000000,952,8487561,Paid
14132,14133,9.522023e+20,2023-07-10,2023-07-10,2023-07-24,R,R INFRATECH,INDIA,PRIVATE LIM,TL,2682,1000000,952,8487561,Paid
14133,14134,9.522023e+20,2023-07-10,2023-07-10,2023-07-24,R,R INFRATECH,INDIA,PRIVATE LIM,TL,2648,1000000,952,8487561,Paid
14134,14135,9.522023e+20,2023-07-10,2023-07-10,2023-07-24,R,R INFRATECH,INDIA,PRIVATE LIM,TL,2616,1000000,952,8487561,Paid
14135,14136,9.522023e+20,2023-07-10,2023-07-10,2023-07-24,R,R INFRATECH,INDIA,PRIVATE LIM,TL,2672,1000000,952,8487561,Paid
18232,18233,1.202401e+18,2024-01-08,2024-01-08,2024-01-22,PRAKASH DISTILLERY & CHEMICAL CO (P) LT,,,D,TL,15987,1000000,1,5898161,Paid
18233,18234,1.202401e+18,2024-01-08,2024-01-08,2024-01-22,PRAKASH DISTILLERY & CHEMICAL CO (P) LT,,,D,TL,15993,1000000,1,5898161,Paid
18234,18235,1.202401e+18,2024-01-08,2024-01-08,2024-01-22,PRAKASH DISTILLERY & CHEMICAL CO (P) LT,,,D,TL,15991,1000000,1,5898161,Paid
18235,18236,1.202401e+18,2024-01-08,2024-01-08,2024-01-22,PRAKASH DISTILLERY & CHEMICAL CO (P) LT,,,D,TL,15989,1000000,1,5898161,Paid
18236,18237,1.202401e+18,2024-01-08,2024-01-08,2024-01-22,PRAKASH DISTILLERY & CHEMICAL CO (P) LT,,,D,TL,15981,1000000,1,5898161,Paid
18237,18238,1.202401e+18,2024-01-08,2024-01-08,2024-01-22,PRAKASH DISTILLERY & CHEMICAL CO (P) LT,,,D,TL,15983,1000000,1,5898161,Paid
18238,18239,1.202401e+18,2024-01-08,2024-01-08,2024-01-22,PRAKASH DISTILLERY & CHEMICAL CO (P) LT,,,D,TL,15995,1000000,1,5898161,Paid
18239,18240,1.202401e+18,2024-01-08,2024-01-08,2024-01-22,PRAKASH DISTILLERY & CHEMICAL CO (P) LT,,,D,TL,15985,1000000,1,5898161,Paid

In [41]:
# joining name in column 7,8,9 and name of the purchaser

In [43]:
df["Name of the Purchaser"] = df["Name of the Purchaser"] + " " + df["Column7"] + " " + df["Column8"] + " " + df["Column9"]

In [44]:
df.loc[x]

,Sr No.,Reference No (URN),Journal Date,Date of\nPurchase,Date of Expiry,Name of the Purchaser,Column7,Column8,Column9,Prefix,Bond\nNumber,Denominations,Issue Branch Code,Issue Teller,Status
12330,12331,3.002023e+20,2023-04-06,2023-04-06,2023-04-20,INDER THAKURDAS JAISINGHANI THAKURDAS JAIS...,,,THAKURDAS JAISINGHANI,OC,13653,10000000,300,7905165,Paid
12331,12332,3.002023e+20,2023-04-06,2023-04-06,2023-04-20,INDER THAKURDAS JAISINGHANI THAKURDAS JAIS...,,,THAKURDAS JAISINGHANI,OC,13661,10000000,300,7905165,Paid
12332,12333,3.002023e+20,2023-04-06,2023-04-06,2023-04-20,INDER THAKURDAS JAISINGHANI THAKURDAS JAIS...,,,THAKURDAS JAISINGHANI,OC,13657,10000000,300,7905165,Paid
12333,12334,3.002023e+20,2023-04-06,2023-04-06,2023-04-20,INDER THAKURDAS JAISINGHANI THAKURDAS JAIS...,,,THAKURDAS JAISINGHANI,OC,13669,10000000,300,7905165,Paid
12334,12335,3.002023e+20,2023-04-06,2023-04-06,2023-04-20,INDER THAKURDAS JAISINGHANI THAKURDAS JAIS...,,,THAKURDAS JAISINGHANI,OC,13659,10000000,300,7905165,Paid
12335,12336,3.002023e+20,2023-04-06,2023-04-06,2023-04-20,INDER THAKURDAS JAISINGHANI THAKURDAS JAIS...,,,THAKURDAS JAISINGHANI,OC,13667,10000000,300,7905165,Paid
12336,12337,3.002023e+20,2023-04-06,2023-04-06,2023-04-20,INDER THAKURDAS JAISINGHANI THAKURDAS JAIS...,,,THAKURDAS JAISINGHANI,OC,13655,10000000,300,7905165,Paid
12337,12338,3.002023e+20,2023-04-06,2023-04-06,2023-04-20,INDER THAKURDAS JAISINGHANI THAKURDAS JAIS...,,,THAKURDAS JAISINGHANI,OC,13651,10000000,300,7905165,Paid
12338,12339,3.002023e+20,2023-04-06,2023-04-06,2023-04-20,INDER THAKURDAS JAISINGHANI THAKURDAS JAIS...,,,THAKURDAS JAISINGHANI,OC,13663,10000000,300,7905165,Paid
12339,12340,3.002023e+20,2023-04-06,2023-04-06,2023-04-20,INDER THAKURDAS JAISINGHANI THAKURDAS JAIS...,,,THAKURDAS JAISINGHANI,OC,13665,10000000,300,7905165,Paid
13438,13439,1.202304e+18,2023-04-12,2023-04-12,2023-04-26,PRAKASH DISTILLERY & CHEMICAL CO (P) LT D D,,,D,TL,14654,1000000,1,5054982,Paid
13439,13440,1.202304e+18,2023-04-12,2023-04-12,2023-04-26,PRAKASH DISTILLERY & CHEMICAL CO (P) LT D D,,,D,TL,14656,1000000,1,5054982,Paid
13440,13441,1.202304e+18,2023-04-12,2023-04-12,2023-04-26,PRAKASH DISTILLERY & CHEMICAL CO (P) LT D D,,,D,TL,14658,1000000,1,5054982,Paid
13441,13442,1.202304e+18,2023-04-12,2023-04-12,2023-04-26,PRAKASH DISTILLERY & CHEMICAL CO (P) LT D D,,,D,TL,14650,1000000,1,5054982,Paid
13442,13443,1.202304e+18,2023-04-12,2023-04-12,2023-04-26,PRAKASH DISTILLERY & CHEMICAL CO (P) LT D D,,,D,TL,14652,1000000,1,5054982,Paid
14120,14121,9.522023e+20,2023-07-10,2023-07-10,2023-07-24,R R INFRATECH INDIA PRIVATE LIM R INFRATECH IN...,R INFRATECH,INDIA,PRIVATE LIM,OC,1252,10000000,952,8487561,Paid
14121,14122,9.522023e+20,2023-07-10,2023-07-10,2023-07-24,R R INFRATECH INDIA PRIVATE LIM R INFRATECH IN...,R INFRATECH,INDIA,PRIVATE LIM,TL,2697,1000000,952,8487561,Paid
14122,14123,9.522023e+20,2023-07-10,2023-07-10,2023-07-24,R R INFRATECH INDIA PRIVATE LIM R INFRATECH IN...,R INFRATECH,INDIA,PRIVATE LIM,TL,2647,1000000,952,8487561,Paid
14123,14124,9.522023e+20,2023-07-10,2023-07-10,2023-07-24,R R INFRATECH INDIA PRIVATE LIM R INFRATECH IN...,R INFRATECH,INDIA,PRIVATE LIM,TL,2677,1000000,952,8487561,Paid
14124,14125,9.522023e+20,2023-07-10,2023-07-10,2023-07-24,R R INFRATECH INDIA PRIVATE LIM R INFRATECH IN...,R INFRATECH,INDIA,PRIVATE LIM,TL,2695,1000000,952,8487561,Paid
14125,14126,9.522023e+20,2023-07-10,2023-07-10,2023-07-24,R R INFRATECH INDIA PRIVATE LIM R INFRATECH IN...,R INFRATECH,INDIA,PRIVATE LIM,TL,2663,1000000,952,8487561,Paid
14126,14127,9.522023e+20,2023-07-10,2023-07-10,2023-07-24,R R INFRATECH INDIA PRIVATE LIM R INFRATECH IN...,R INFRATECH,INDIA,PRIVATE LIM,TL,2660,1000000,952,8487561,Paid
14127,14128,9.522023e+20,2023-07-10,2023-07-10,2023-07-24,R R INFRATECH INDIA PRIVATE LIM R INFRATECH IN...,R INFRATECH,INDIA,PRIVATE LIM,TL,2603,1000000,952,8487561,Paid
14128,14129,9.522023e+20,2023-07-10,2023-07-10,2023-07-24,R R INFRATECH INDIA PRIVATE LIM R INFRATECH IN...,R INFRATECH,INDIA,PRIVATE LIM,TL,2625,1000000,952,8487561,Paid
14129,14130,9.522023e+20,2023-07-10,2023-07-10,2023-07-24,R R INFRATECH INDIA PRIVATE LIM R INFRATECH IN...,R INFRATECH,INDIA,PRIVATE LIM,TL,2690,1000000,952,8487561,Paid
14130,14131,9.522023e+20,2023-07-10,2023-07-10,2023-07-24,R R INFRATECH INDIA PRIVATE LIM R INFRATECH IN...,R INFRATECH,INDIA,PRIVATE LIM,TL,2675,1000000,952,8487561,Paid
14131,14132,9.522023e+20,2023-07-10,2023-07-10,2023-07-24,R R INFRATECH INDIA PRIVATE LIM R INFRATECH IN...,R INFRATECH,INDIA,PRIVATE LIM,TL,2693,1000000,952,8487561,Paid
14132,14133,9.522023e+20,2023-07-10,2023-07-10,2023-07-24,R R INFRATECH INDIA PRIVATE LIM R INFRATECH IN...,R INFRATECH,INDIA,PRIVATE LIM,TL,2682,1000000,952,8487561,Paid
14133,14134,9.522023e+20,2023-07-10,2023-07-10,2023-07-24,R R INFRATECH INDIA PRIVATE LIM R INFRATECH IN...,R INFRATECH,INDIA,PRIVATE LIM,TL,2648,1000000,952,8487561,Paid
14134,14135,9.522023e+20,2023-07-10,2023-07-10,2023-07-24,R R INFRATECH INDIA PRIVATE LIM R INFRATECH IN...,R INFRATECH,INDIA,PRIVATE LIM,TL,2616,1000000,952,8487561,Paid
14135,14136,9.522023e+20,2023-07-10,2023-07-10,2023-07-24,R R INFRATECH INDIA PRIVATE LIM R INFRATECH IN...,R INFRATECH,INDIA,PRIVATE LIM,TL,2672,1000000,952,8487561,Paid
18232,18233,1.202401e+18,2024-01-08,2024-01-08,2024-01-22,PRAKASH DISTILLERY & CHEMICAL CO (P) LT D D,,,D,TL,15987,1000000,1,5898161,Paid
18233,18234,1.202401e+18,2024-01-08,2024-01-08,2024-01-22,PRAKASH DISTILLERY & CHEMICAL CO (P) LT D D,,,D,TL,15993,1000000,1,5898161,Paid
18234,18235,1.202401e+18,2024-01-08,2024-01-08,2024-01-22,PRAKASH DISTILLERY & CHEMICAL CO (P) LT D D,,,D,TL,15991,1000000,1,5898161,Paid
18235,18236,1.202401e+18,2024-01-08,2024-01-08,2024-01-22,PRAKASH DISTILLERY & CHEMICAL CO (P) LT D D,,,D,TL,15989,1000000,1,5898161,Paid
18236,18237,1.202401e+18,2024-01-08,2024-01-08,2024-01-22,PRAKASH DISTILLERY & CHEMICAL CO (P) LT D D,,,D,TL,15981,1000000,1,5898161,Paid
18237,18238,1.202401e+18,2024-01-08,2024-01-08,2024-01-22,PRAKASH DISTILLERY & CHEMICAL CO (P) LT D D,,,D,TL,15983,1000000,1,5898161,Paid
18238,18239,1.202401e+18,2024-01-08,2024-01-08,2024-01-22,PRAKASH DISTILLERY & CHEMICAL CO (P) LT D D,,,D,TL,15995,1000000,1,5898161,Paid
18239,18240,1.202401e+18,2024-01-08,2024-01-08,2024-01-22,PRAKASH DISTILLERY & CHEMICAL CO (P) LT D D,,,D,TL,15985,1000000,1,5898161,Paid

In [45]:
df.drop(["Column7","Column8","Column9"],axis = 1, inplace = True)

In [48]:
df.loc[x]

,Sr No.,Reference No (URN),Journal Date,Date of\nPurchase,Date of Expiry,Name of the Purchaser,Prefix,Bond\nNumber,Denominations,Issue Branch Code,Issue Teller,Status
12330,12331,3.002023e+20,2023-04-06,2023-04-06,2023-04-20,INDER THAKURDAS JAISINGHANI THAKURDAS JAIS...,OC,13653,10000000,300,7905165,Paid
12331,12332,3.002023e+20,2023-04-06,2023-04-06,2023-04-20,INDER THAKURDAS JAISINGHANI THAKURDAS JAIS...,OC,13661,10000000,300,7905165,Paid
12332,12333,3.002023e+20,2023-04-06,2023-04-06,2023-04-20,INDER THAKURDAS JAISINGHANI THAKURDAS JAIS...,OC,13657,10000000,300,7905165,Paid
12333,12334,3.002023e+20,2023-04-06,2023-04-06,2023-04-20,INDER THAKURDAS JAISINGHANI THAKURDAS JAIS...,OC,13669,10000000,300,7905165,Paid
12334,12335,3.002023e+20,2023-04-06,2023-04-06,2023-04-20,INDER THAKURDAS JAISINGHANI THAKURDAS JAIS...,OC,13659,10000000,300,7905165,Paid
12335,12336,3.002023e+20,2023-04-06,2023-04-06,2023-04-20,INDER THAKURDAS JAISINGHANI THAKURDAS JAIS...,OC,13667,10000000,300,7905165,Paid
12336,12337,3.002023e+20,2023-04-06,2023-04-06,2023-04-20,INDER THAKURDAS JAISINGHANI THAKURDAS JAIS...,OC,13655,10000000,300,7905165,Paid
12337,12338,3.002023e+20,2023-04-06,2023-04-06,2023-04-20,INDER THAKURDAS JAISINGHANI THAKURDAS JAIS...,OC,13651,10000000,300,7905165,Paid
12338,12339,3.002023e+20,2023-04-06,2023-04-06,2023-04-20,INDER THAKURDAS JAISINGHANI THAKURDAS JAIS...,OC,13663,10000000,300,7905165,Paid
12339,12340,3.002023e+20,2023-04-06,2023-04-06,2023-04-20,INDER THAKURDAS JAISINGHANI THAKURDAS JAIS...,OC,13665,10000000,300,7905165,Paid
13438,13439,1.202304e+18,2023-04-12,2023-04-12,2023-04-26,PRAKASH DISTILLERY & CHEMICAL CO (P) LT D D,TL,14654,1000000,1,5054982,Paid
13439,13440,1.202304e+18,2023-04-12,2023-04-12,2023-04-26,PRAKASH DISTILLERY & CHEMICAL CO (P) LT D D,TL,14656,1000000,1,5054982,Paid
13440,13441,1.202304e+18,2023-04-12,2023-04-12,2023-04-26,PRAKASH DISTILLERY & CHEMICAL CO (P) LT D D,TL,14658,1000000,1,5054982,Paid
13441,13442,1.202304e+18,2023-04-12,2023-04-12,2023-04-26,PRAKASH DISTILLERY & CHEMICAL CO (P) LT D D,TL,14650,1000000,1,5054982,Paid
13442,13443,1.202304e+18,2023-04-12,2023-04-12,2023-04-26,PRAKASH DISTILLERY & CHEMICAL CO (P) LT D D,TL,14652,1000000,1,5054982,Paid
14120,14121,9.522023e+20,2023-07-10,2023-07-10,2023-07-24,R R INFRATECH INDIA PRIVATE LIM R INFRATECH IN...,OC,1252,10000000,952,8487561,Paid
14121,14122,9.522023e+20,2023-07-10,2023-07-10,2023-07-24,R R INFRATECH INDIA PRIVATE LIM R INFRATECH IN...,TL,2697,1000000,952,8487561,Paid
14122,14123,9.522023e+20,2023-07-10,2023-07-10,2023-07-24,R R INFRATECH INDIA PRIVATE LIM R INFRATECH IN...,TL,2647,1000000,952,8487561,Paid
14123,14124,9.522023e+20,2023-07-10,2023-07-10,2023-07-24,R R INFRATECH INDIA PRIVATE LIM R INFRATECH IN...,TL,2677,1000000,952,8487561,Paid
14124,14125,9.522023e+20,2023-07-10,2023-07-10,2023-07-24,R R INFRATECH INDIA PRIVATE LIM R INFRATECH IN...,TL,2695,1000000,952,8487561,Paid
14125,14126,9.522023e+20,2023-07-10,2023-07-10,2023-07-24,R R INFRATECH INDIA PRIVATE LIM R INFRATECH IN...,TL,2663,1000000,952,8487561,Paid
14126,14127,9.522023e+20,2023-07-10,2023-07-10,2023-07-24,R R INFRATECH INDIA PRIVATE LIM R INFRATECH IN...,TL,2660,1000000,952,8487561,Paid
14127,14128,9.522023e+20,2023-07-10,2023-07-10,2023-07-24,R R INFRATECH INDIA PRIVATE LIM R INFRATECH IN...,TL,2603,1000000,952,8487561,Paid
14128,14129,9.522023e+20,2023-07-10,2023-07-10,2023-07-24,R R INFRATECH INDIA PRIVATE LIM R INFRATECH IN...,TL,2625,1000000,952,8487561,Paid
14129,14130,9.522023e+20,2023-07-10,2023-07-10,2023-07-24,R R INFRATECH INDIA PRIVATE LIM R INFRATECH IN...,TL,2690,1000000,952,8487561,Paid
14130,14131,9.522023e+20,2023-07-10,2023-07-10,2023-07-24,R R INFRATECH INDIA PRIVATE LIM R INFRATECH IN...,TL,2675,1000000,952,8487561,Paid
14131,14132,9.522023e+20,2023-07-10,2023-07-10,2023-07-24,R R INFRATECH INDIA PRIVATE LIM R INFRATECH IN...,TL,2693,1000000,952,8487561,Paid
14132,14133,9.522023e+20,2023-07-10,2023-07-10,2023-07-24,R R INFRATECH INDIA PRIVATE LIM R INFRATECH IN...,TL,2682,1000000,952,8487561,Paid
14133,14134,9.522023e+20,2023-07-10,2023-07-10,2023-07-24,R R INFRATECH INDIA PRIVATE LIM R INFRATECH IN...,TL,2648,1000000,952,8487561,Paid
14134,14135,9.522023e+20,2023-07-10,2023-07-10,2023-07-24,R R INFRATECH INDIA PRIVATE LIM R INFRATECH IN...,TL,2616,1000000,952,8487561,Paid
14135,14136,9.522023e+20,2023-07-10,2023-07-10,2023-07-24,R R INFRATECH INDIA PRIVATE LIM R INFRATECH IN...,TL,2672,1000000,952,8487561,Paid
18232,18233,1.202401e+18,2024-01-08,2024-01-08,2024-01-22,PRAKASH DISTILLERY & CHEMICAL CO (P) LT D D,TL,15987,1000000,1,5898161,Paid
18233,18234,1.202401e+18,2024-01-08,2024-01-08,2024-01-22,PRAKASH DISTILLERY & CHEMICAL CO (P) LT D D,TL,15993,1000000,1,5898161,Paid
18234,18235,1.202401e+18,2024-01-08,2024-01-08,2024-01-22,PRAKASH DISTILLERY & CHEMICAL CO (P) LT D D,TL,15991,1000000,1,5898161,Paid
18235,18236,1.202401e+18,2024-01-08,2024-01-08,2024-01-22,PRAKASH DISTILLERY & CHEMICAL CO (P) LT D D,TL,15989,1000000,1,5898161,Paid
18236,18237,1.202401e+18,2024-01-08,2024-01-08,2024-01-22,PRAKASH DISTILLERY & CHEMICAL CO (P) LT D D,TL,15981,1000000,1,5898161,Paid
18237,18238,1.202401e+18,2024-01-08,2024-01-08,2024-01-22,PRAKASH DISTILLERY & CHEMICAL CO (P) LT D D,TL,15983,1000000,1,5898161,Paid
18238,18239,1.202401e+18,2024-01-08,2024-01-08,2024-01-22,PRAKASH DISTILLERY & CHEMICAL CO (P) LT D D,TL,15995,1000000,1,5898161,Paid
18239,18240,1.202401e+18,2024-01-08,2024-01-08,2024-01-22,PRAKASH DISTILLERY & CHEMICAL CO (P) LT D D,TL,15985,1000000,1,5898161,Paid

In [49]:
df.rename({"Date of\nPurchase":"Date of Purchase"},axis=1, inplace = True)

In [54]:
df.loc[df["Bond\nNumber"]==1098]

,Sr No.,Reference No (URN),Journal Date,Date of Purchase,Date of Expiry,Name of the Purchaser,Prefix,Bond\nNumber,Denominations,Issue Branch Code,Issue Teller,Status
2774,2775,8.132019e+20,2019-10-05,2019-10-05,2019-10-19,PRESTIGE NOTTING HILL INVESTMENTS,OC,1098,10000000,813,5144485,Paid
10040,10041,6.282022e+20,2022-10-10,2022-10-10,2022-10-24,AVON CYCLES LTD,TL,1098,1000000,628,5809436,Paid

In [55]:
df["pkey"] = df["Prefix"] + "-" + df["Bond\nNumber"].astype(str)

In [57]:
df.drop(["Prefix","Bond\nNumber"],axis =1, inplace = True)

In [58]:
df["Name of the Purchase"].value_counts().reset_index()

KeyError: 'Name of the Purchase'